name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [created]

permissions:
  contents: write

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Arm Toolchain
        run: sudo apt-get -y install gcc-arm-none-eabi

      - name: Configure CMake
        run: cmake -DCMAKE_TOOLCHAIN_FILE=lib/libDaisy/cmake/toolchains/stm32h750xx.cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -B build

      - name: Build
        run: cmake --build build --config ${{env.BUILD_TYPE}}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: build/TerrariumTest.bin
          retention-days: 7

      - name: Upload Release
        if: ${{ github.event_name == 'release' && github.event.action == 'created' }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: gh release upload ${{github.ref_name}} build/TerrariumTest.bin
